import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored: copied verbatim from registries (shadcn / ai-elements /
    // better-auth-ui) - not our code, do not lint.
    "src/components/ai-elements/**",
    "src/components/auth/**",
    "src/hooks/use-mobile.ts",
    // Generated by drizzle-kit.
    "drizzle/**",
  ]),
]);

export default eslintConfig;
